import { z } from "zod";
import { MAX_FILES_PER_REQUEST, uploadFileSchema, uploadFilesSchema } from "../../lib/uploadRules";

// --- guest

export const guestBatchParamsSchema = z.object({
  token: z.string().min(20).max(100),
  batchId: z.uuid(),
});

export const createBatchSchema = z.object({
  // Generated by the client once per upload attempt; resending it returns the same batch.
  idempotencyKey: z.string().regex(/^[A-Za-z0-9_-]{8,100}$/, "8-100 letters, digits, - or _"),
  // A short blessing for the couple (150 characters).
  message: z.string().trim().min(1).max(150).optional(),
  files: z
    .array(uploadFileSchema.extend({ note: z.string().trim().min(1).max(200).optional() }))
    .min(1)
    .max(MAX_FILES_PER_REQUEST),
});

// --- host (direct upload)

export const hostPresignSchema = z.object({ files: uploadFilesSchema });

export const hostCompleteSchema = z.object({
  files: z
    .array(uploadFileSchema.extend({ photoId: z.uuid() }))
    .min(1)
    .max(20),
});

export type CreateBatchInput = z.infer<typeof createBatchSchema>;
export type HostPresignInput = z.infer<typeof hostPresignSchema>;
export type HostCompleteInput = z.infer<typeof hostCompleteSchema>;
